language: python 

services: 
  - postgresql

python:
  - "3.6"

install: 
  - pip install -r requirements.txt 
  - pip install coveralls

before_script: 
  - psql -c "CREATE DATABASE test_standup;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres
  -  pip install coverage

script:
  - python manage.py test
  - coverage run --source='.' manage.py test app

after_success:
  - coveralls