# Generated by Django 2.2.4 on 2020-06-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=235)),
                ('second_name', models.CharField(max_length=235)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=235)),
            ],
        ),
    ]
