# Generated by Django 2.2.4 on 2020-06-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Author',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-email']},
        ),
    ]
